services:
#    my_app_billetterie.example:
#        class: MyApp\BilletterieBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     my_app_billetterie.coderesa:
        class: MyApp\BilletterieBundle\Command\GenCodeResa

     my_app_billetterie.limitebillet:
        class: MyApp\BilletterieBundle\Command\limiteBillet


