<?php

namespace MyApp\BilletterieBundle\Repository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends \Doctrine\ORM\EntityRepository
{
    public function sumMontant($id)
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('SUM(b.montant) AS montantTotal')
            ->where('b.commande = :id')
            ->setParameter(':id', $id);

        return $qb
            ->getQuery()
            ->getSingleScalarResult()
            //->getResult()
            ;
    }
}
