<?php

namespace MyApp\BilletterieBundle\Repository;

/**
 * typeTarifsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeTarifsRepository extends \Doctrine\ORM\EntityRepository
{
}
